update ci, fix os_misc.c

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -8,15 +8,14 @@ jobs:
   build:
     strategy:
       matrix:
-        arch: [ "arm32", "aarch64" ]
+        arch: [ "arm32", "aarch64", "x86_64" ]
       fail-fast: false
 
     name: "Build for ${{matrix.arch}}"
 
     runs-on: ubuntu-latest
 
-    steps:
-        
+    steps:        
       - uses: actions/checkout@v2
 
       - name: Build
@@ -44,11 +43,16 @@ jobs:
           ninja -C "build-android" install
           cd ..
           envsubst <android-${{matrix.arch}} >build-crossfile
+          git clone --depth 1 https://gitlab.freedesktop.org/mesa/mesa.git
+          cd mesa
+          wget https://gitlab.freedesktop.org/mesa/mesa/-/commit/bed69133cda5bb6e29beacd61a665ef653d4d1f9.diff
+          git apply -v --whitespace=fix --reverse bed69133cda5bb6e29beacd61a665ef653d4d1f9.diff || echo "git apply failed"
+          git apply -v --whitespace=fix ../mesa-zink.diff || echo "git apply failed"
           meson setup "build-android" \
             --prefix=/tmp/mesa \
-            --cross-file "build-crossfile" \
+            --cross-file "../build-crossfile" \
             -Dplatforms=android \
-            -Dplatform-sdk-version=26 \
+            -Dplatform-sdk-version=25 \
             -Dandroid-stub=true \
             -Dllvm=disabled \
             -Dxlib-lease=disabled \
@@ -61,8 +65,14 @@ jobs:
             -Dgallium-drivers=freedreno,zink \
             -Dfreedreno-kmds=kgsl \
             -Dshared-glapi=false \
+            -Dandroid-libbacktrace=disabled \
             -Dbuildtype=release
-          ninja -C "build-android" install
+          cd build-android
+          if [ ${{matrix.arch}} == 'x86_64' ]
+          then
+            meson configure -Dgallium-drivers=zink
+          fi
+          ninja install
       - name: Upload libraries
         uses: actions/upload-artifact@v2
         with:
